version: "3.1"
services:
    memcached:
      image: memcached:alpine
      container_name: comments-memcached

    redis:
      image: redis:alpine
      container_name: comments-redis

    postgres:
      image: postgres:11.1-alpine
      container_name: comments-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=test
        - POSTGRES_DB=comments
      ports:
        - "7781:5432"

    webserver:
      image: nginx:alpine
      container_name: comments-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "7777:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: comments-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

